// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'This platform is not supported by Firebase.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqBolfz-4bPsmPrBjeSKP-LVnC-Hp5KgA',
    appId: '1:742665584670:web:62ec49df6ce066fc976e0f',
    messagingSenderId: '742665584670',
    projectId: 'sruja-railway',
    authDomain: 'sruja-railway.firebaseapp.com',
    storageBucket: 'sruja-railway.firebasestorage.app',
    measurementId: 'G-4B8DRHFYVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADliyjXJBJQi3YuP5YR9t0BmFVDZRtp9c',
    appId: '1:742665584670:android:3e46defa3a1301e9976e0f',
    messagingSenderId: '742665584670',
    projectId: 'sruja-railway',
    storageBucket: 'sruja-railway.firebasestorage.app',
  );

}